# Generated by Django 5.2.9 on 2025-12-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
