# Generated by Django 5.2.9 on 2025-12-16 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('completed', 'Realizado'), ('cancelled', 'Cancelado'), ('no_show', 'Não compareceu')], default='scheduled', max_length=20)),
                ('appointment_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('ai_suggested', models.BooleanField(default=False)),
                ('priority_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['date_time'],
                'indexes': [models.Index(fields=['doctor', 'date_time'], name='appointment_doctor__1c115c_idx'), models.Index(fields=['patient', 'date_time'], name='appointment_patient_bce84f_idx')],
            },
        ),
    ]
