# Generated by Django 5.2.9 on 2025-12-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_address_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='neighborhood',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='number',
            field=models.CharField(default='', max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='', max_length=2, verbose_name='Estado (UF)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(default='', max_length=255, verbose_name='Rua/Avenida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='zipcode',
            field=models.CharField(default='', max_length=10, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
